[package]
name = "docker-fetch"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
colorize = "0.1.0"
figlet-rs = "0.1.5"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
